### PR TITLE
Add support to payloads when binding view holder

### PR DESCRIPTION
**Pull request by igoriols**
Hi, I made some changes to support payloads when binding view holder.

I couldn't format the code very well, can you take a look?

Thanks in advance.

### CODE REVIEW

**Comment by sockeqwe** [comment]
Hi,
thanks for your pull request. Unfortunately I'm very busy at the moment. I will have a look at your pull request in August, but it seems to introduce breaking changes that may be part of a major `3.0.0` release

**Comment by igoriols** [comment]
Hi Hannes! I will wait for 3.0.0 release then.

Thanks again!

**Comment by sockeqwe** [comment]
@igoriols I might be wrong, but there is still a need for `onBindViewHolder(VH, int)` (without payload). There must be both versions, right?

**Comment by igoriols** [comment]
@sockeqwe If you call `notifyItemChanged(position)` it calls `notifyItemChanged(position, null)` (null as payload) internally. So it is fine for me passing null. And yes, there must be both versions (with or without payload).

Based on how it is designed today it is ok for me. @yigit Can you give us some help about the future changes?

**Comment by sockeqwe** [comment]
This has already been merged and released in Version 3.0.0 . Payload is
empty list if it notifyItemChanged() has been called without payload...

Igor Oliveira <notifications@github.com> schrieb am Fr., 14. Okt. 2016,
18:29:

**Comment by yigit** [comment]
RecyclerView internally always calls onBind(vh, int, payload) which delegates to the 2 arg method. As long as you override the 3 arg method, you are guaranteed to receive all calls. 
As clarified in the documentation, `onBind`'s payload is non-null so you cannot pass null for it, you have to pass empty list if you don't have it.

**Comment by sockeqwe** [comment]
thanks @yigit  for the clarification!

**Pull request merged**
