### PR TITLE
added support for headers to AdapterDelegatesManager

### PR DESCRIPTION
**Pull request by Fishfield**
To support headers for 'RecyclerView' I added the ability to add headers into the `AdapterDelegatesManager`. Before it was only possible to use a header with adding it to the items data source.

### CODE REVIEW

**Comment by sockeqwe** [comment]
Thanks for your pull request, I will take a look during christmas holidays.

**Comment by sockeqwe** [comment]
I'm sorry, but I think that there are some major issues with this API.

1. I do think that adding a header as part of the adpater's dataset is the best and the least error prone way for adding headers (and moreover,  the simplest way to debug your adapter since everything is present in your adapter's dataset).
2. If you really don't want to have headers in your dataset you could simply write an adapter that `adapter.getItemCount()` returns the dataset size +1 and then register your `HeaderAdapterDelegate` with `isForViewType()`implementation that checks if `position == 0` (so that it is the first item and therefore a header). So there is no need to add an `addHeader()` method.
3. `addHeader()` could be called more than once. `hasHeader ? position - 1 : position` is very fragile in this context. Do we want to support multiple headers (some kind of section headers)? If yes, I have no clue how such an implementation looks like.

Overall, I don't think that adding header support is a good idea. I think that this is a specific edge case (i.e. what about sections and section headers?) and I'm sure that this is one reason why the android team haven't added support for headers directly in RecyclerView at first place.

What do you think?

**Comment by Fishfield** [comment]
Hey,
I actually first copied the needed parts of your code into our project, so that I could add the header. Then one of my colleagues said I should do a pull request that we can use the library directly, so yes you are completely right the code is a little fragile,.... 

The initial idea why I added the support for a header was because I think it is kind of wrong to add a header to the adapter's dataset and this can also be very error prone.

Nevertheless I'll try the solution you mentioned in 2 and let you know if I will succeed.
Thanks for your useful input. I guess this pull request can be closed now.

**Comment by Fishfield** [comment]
So I now implemented the solution with the adapter returning dataset size +1. It works fine and was easy to change, but it has some drawbacks:

1. It is not possible to use `AbsListItemAdapterDelegate` anymore, as the function `isForViewType` will throw an `IndexOutOfBoundsException`.
2. With the `AdapterDelegate` implementation you have to be aware of the position. Every time the position is used in the concrete adapter you need to subtract 1 (`position--`) as the size is +1 because of the header, which can be really error prone and cumbersome.

**Pull request closed without merging**
