### PR TITLE
Getting `Protected function call from public-API inline function is prohibited` with Kotlin 1.4.0

### PR DESCRIPTION
**Pull request by vanniktech**
https://github.com/sockeqwe/AdapterDelegates/issues/89 is no longer working for me

### CODE REVIEW

**Comment by sockeqwe** [comment]
Thanks for this.
But making it public would break too many apps out there (everyone would need to change their AdapterDelegates from protected to public if I'm not mistaken). I think we could wrap the AdapterDelegates into a public API version just for the inline DSL functions. This should solve calling protected methods from Inline dunctions and should not break all other AdapterDelegates out there. Will give it a try tomorrow.

**Comment by sockeqwe** [comment]
Wait, I just checked it the demo app and it compiles just fine with Kotlin 1.4.0.

I think I dont understand what your "modification does" so that it requires to make these methods to be public. Can you explain?

**Comment by vanniktech** [comment]
```
package com.hannesdorfmann.adapterdelegates4

import android.view.ViewGroup
import androidx.recyclerview.widget.RecyclerView
import com.hannesdorfmann.adapterdelegates4.dsl.AdapterDelegateViewHolder

@Suppress("UNCHECKED_CAST", "PROTECTED_CALL_FROM_PUBLIC_INLINE")
inline fun <Old, reified I : T, T> AdapterDelegate<List<Old>>.wrap(noinline mapper: (I) -> Old): AdapterDelegate<List<T>> {
  val listItemAdapterDelegate = this as AbsListItemAdapterDelegate<Old, Old, AdapterDelegateViewHolder<Old>>
  return object : AbsListItemAdapterDelegate<I, T, RecyclerView.ViewHolder>() {
    override fun isForViewType(item: T, items: MutableList<T>, position: Int): Boolean = item is I

    override fun onBindViewHolder(item: I, holder: RecyclerView.ViewHolder, payloads: MutableList<Any>) {
      listItemAdapterDelegate.onBindViewHolder(mapper.invoke(item), holder as AdapterDelegateViewHolder<Old>, payloads)
    }

    override fun onCreateViewHolder(parent: ViewGroup) = listItemAdapterDelegate.onCreateViewHolder(parent)
  }
}
```

Screenshot 2020-08-25 at 06 26 25

**Comment by vanniktech** [comment]
I forked and made those methods public :/ 

Is there any update from your side?

**Comment by sockeqwe** [comment]
Not yet, haven't had time to work kn next version

Niklas Baudy <notifications@github.com> schrieb am Mi., 11. Nov. 2020,
20:41:

**Comment by vanniktech** [comment]
No longer need this 🤷

**Pull request closed without merging**
