### PR TITLE
Changes field modifiers to protected to allow subclassing.

### PR DESCRIPTION
**Pull request by rubenweerts**
Also fixes a small typo in comment

### CODE REVIEW

**Comment by sockeqwe** [comment]
Thanks for this pull request.
I'm willing to accept that but I wanted to ask why public methods like `addDelegate()` `setFallbackDelegate()` is not enough? You can invoke them from subclasses too ...

**Comment by rubenweerts** [comment]
When you want to read all delegates it's handy to access the SparseArray. I was in the process of building something that the DelegatesManager automatically adds missing delegates.

**Comment by sockeqwe** [comment]
Ok, thanks!
 
`2.0.2-SNAPSHOT` will be deployed automatically in a few minutes from travis ci. So you can use that in the mean time ...

**Comment by rubenweerts** [comment]
👍  super

**Comment by veyndan** [comment]
Why would `fallbackDelegate` need to be set to `protected`? There is already a getter and a setter provided for it.

Also, why break encapsulation by elevating `delegates` to have a modifier of `protected` instead of just providing a getter (and potentially a setter)?

**Comment by sockeqwe** [comment]
Yeah, maybe we should revisit the decision ... Maybe adding just a getter method to access all registered delegates or offering an iterator is enough ...

**Comment by veyndan** [comment]
As `SparseArrayCompat` doesn't implement `Iterable`, I think providing a getter for `delegates` directly would be preferable.

**Pull request merged**
