### PR TITLE
Generate layout with viewholder layout id rather than array size

### PR DESCRIPTION
**Pull request by theshapguy**
The tests are not quite passing yet, any help to get it to pass is appreciated since I'm new to the Android Framework.

Could you take a look over it?

### CODE REVIEW

**Comment by DevAhamed** [comment]
Few concerns: 

1. I think this chage will force all users to change their code since a new abstract method is added.
2. Is there a motivation behind this? If we give layout id's as view type then the user might not be able to use the same layout for different delegates. (very few cases)

**Comment by sockeqwe** [comment]
Thank you @theshapguy for your work.
Why do you think we should add this breaking API change? The advantage is not clear for me. I tend to agree with @DevAhamed .

**Comment by theshapguy** [comment]
I see where you guys are coming from, if the user wanted to they could send a `R.layout.some_layout_file` directly when they are creating the delegate since the `DelegateManager` supports this and would not have to go through the loop. A breaking change would be completely useless for this.. 

credit: late night programming   :tired_face:

**Comment by sockeqwe** [comment]
Yep, you can specify the id when adding the delegate and here you can use
R.layout.foo if you want too.

Shap Guy <notifications@github.com> schrieb am Fr., 16. Juni 2017, 18:38:

**Pull request closed without merging**
